SELECT
  DATE_TRUNC('year', DATE_SUBMITTED_ID) AS review_year,
  COUNT(*) AS total_reviews,
  ROUND(AVG(AVERAGE_RATING), 2) AS avg_rating,
  SUM(CASE WHEN RECOMMENDED = TRUE THEN 1 ELSE 0 END) / COUNT(*) AS pct_recommended
FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED
WHERE AIRLINE = 'United Airlines'
GROUP BY DATE_TRUNC('year', DATE_SUBMITTED_ID)
ORDER BY review_year;
