SELECT
    DATE_TRUNC('year', DATE_SUBMITTED_ID) AS review_year,
    ROUND(AVG(SEAT_COMFORT), 2) AS avg_seat_comfort,
    ROUND(AVG(FOOD_AND_BEVERAGES), 2) AS avg_food,
    ROUND(AVG(INFLIGHT_ENTERTAINMENT), 2) AS avg_entertainment
FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED
WHERE AIRLINE = 'United Airlines'
GROUP BY DATE_TRUNC('year', DATE_SUBMITTED_ID)
ORDER BY review_year;