SELECT
    DATE_TRUNC('year', DATE_SUBMITTED_ID) AS review_year,
    ROUND(AVG(CABIN_STAFF_SERVICE), 2) AS avg_cabin_staff,
    ROUND(AVG(GROUND_SERVICE), 2) AS avg_ground,
FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED
WHERE AIRLINE = 'United Airlines'
GROUP BY DATE_TRUNC('year', DATE_SUBMITTED_ID)
ORDER BY review_year;
