SELECT
    TO_CHAR(DATE_SUBMITTED_ID, 'YYYY') AS review_year,
    ROUND(AVG(CABIN_STAFF_SERVICE), 2) AS avg_cabin_staff,
    ROUND(AVG(GROUND_SERVICE), 2) AS avg_ground,
FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED
WHERE AIRLINE = 'United Airlines'
GROUP BY TO_CHAR(DATE_SUBMITTED_ID, 'YYYY')
ORDER BY review_year;
