select s2.AIRCRAFT_ID, s2.AIRCRAFT_MANUFACTURER, s2.AIRCRAFT_MODEL, s2.SEAT_CAPACITY, s1.REVIEW_ID
from SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED as s1
join SKYTRAX_REVIEWS_DB.MARTS.DIM_AIRCRAFT s2
on s1.AIRCRAFT_ID = s2.AIRCRAFT_ID
HAVING AIRLINE = 'United Airlines';