WITH base AS (
  SELECT
    CABIN_STAFF_SERVICE,
    FOOD_AND_BEVERAGES,
    GROUND_SERVICE,
    INFLIGHT_ENTERTAINMENT,
    SEAT_COMFORT,
    WIFI_AND_CONNECTIVITY,
    VALUE_FOR_MONEY
  FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED
  WHERE AIRLINE = 'United Airlines' AND SEAT_TYPE != 'Economy Class'
),
corr_upper AS (
  -- diagonals
  SELECT 'CABIN_STAFF_SERVICE'       AS metric_x, 'CABIN_STAFF_SERVICE'       AS metric_y, 1.0::FLOAT AS correlation UNION ALL
  SELECT 'FOOD_AND_BEVERAGES',              'FOOD_AND_BEVERAGES',                    1.0::FLOAT UNION ALL
  SELECT 'GROUND_SERVICE',                   'GROUND_SERVICE',                       1.0::FLOAT UNION ALL
  SELECT 'INFLIGHT_ENTERTAINMENT',           'INFLIGHT_ENTERTAINMENT',               1.0::FLOAT UNION ALL
  SELECT 'SEAT_COMFORT',                     'SEAT_COMFORT',                         1.0::FLOAT UNION ALL
  SELECT 'WIFI_AND_CONNECTIVITY',            'WIFI_AND_CONNECTIVITY',                1.0::FLOAT UNION ALL
  SELECT 'VALUE_FOR_MONEY',                  'VALUE_FOR_MONEY',                      1.0::FLOAT

  UNION ALL
  -- unique off-diagonal pairs (upper triangle)
  SELECT 'CABIN_STAFF_SERVICE','FOOD_AND_BEVERAGES',        CORR(CABIN_STAFF_SERVICE, FOOD_AND_BEVERAGES)        FROM base UNION ALL
  SELECT 'CABIN_STAFF_SERVICE','GROUND_SERVICE',             CORR(CABIN_STAFF_SERVICE, GROUND_SERVICE)             FROM base UNION ALL
  SELECT 'CABIN_STAFF_SERVICE','INFLIGHT_ENTERTAINMENT',     CORR(CABIN_STAFF_SERVICE, INFLIGHT_ENTERTAINMENT)     FROM base UNION ALL
  SELECT 'CABIN_STAFF_SERVICE','SEAT_COMFORT',               CORR(CABIN_STAFF_SERVICE, SEAT_COMFORT)               FROM base UNION ALL
  SELECT 'CABIN_STAFF_SERVICE','WIFI_AND_CONNECTIVITY',      CORR(CABIN_STAFF_SERVICE, WIFI_AND_CONNECTIVITY)      FROM base UNION ALL
  SELECT 'CABIN_STAFF_SERVICE','VALUE_FOR_MONEY',            CORR(CABIN_STAFF_SERVICE, VALUE_FOR_MONEY)            FROM base UNION ALL

  SELECT 'FOOD_AND_BEVERAGES','GROUND_SERVICE',              CORR(FOOD_AND_BEVERAGES, GROUND_SERVICE)              FROM base UNION ALL
  SELECT 'FOOD_AND_BEVERAGES','INFLIGHT_ENTERTAINMENT',      CORR(FOOD_AND_BEVERAGES, INFLIGHT_ENTERTAINMENT)      FROM base UNION ALL
  SELECT 'FOOD_AND_BEVERAGES','SEAT_COMFORT',                CORR(FOOD_AND_BEVERAGES, SEAT_COMFORT)                FROM base UNION ALL
  SELECT 'FOOD_AND_BEVERAGES','WIFI_AND_CONNECTIVITY',       CORR(FOOD_AND_BEVERAGES, WIFI_AND_CONNECTIVITY)       FROM base UNION ALL
  SELECT 'FOOD_AND_BEVERAGES','VALUE_FOR_MONEY',             CORR(FOOD_AND_BEVERAGES, VALUE_FOR_MONEY)             FROM base UNION ALL

  SELECT 'GROUND_SERVICE','INFLIGHT_ENTERTAINMENT',          CORR(GROUND_SERVICE, INFLIGHT_ENTERTAINMENT)          FROM base UNION ALL
  SELECT 'GROUND_SERVICE','SEAT_COMFORT',                    CORR(GROUND_SERVICE, SEAT_COMFORT)                    FROM base UNION ALL
  SELECT 'GROUND_SERVICE','WIFI_AND_CONNECTIVITY',           CORR(GROUND_SERVICE, WIFI_AND_CONNECTIVITY)           FROM base UNION ALL
  SELECT 'GROUND_SERVICE','VALUE_FOR_MONEY',                 CORR(GROUND_SERVICE, VALUE_FOR_MONEY)                 FROM base UNION ALL

  SELECT 'INFLIGHT_ENTERTAINMENT','SEAT_COMFORT',            CORR(INFLIGHT_ENTERTAINMENT, SEAT_COMFORT)            FROM base UNION ALL
  SELECT 'INFLIGHT_ENTERTAINMENT','WIFI_AND_CONNECTIVITY',   CORR(INFLIGHT_ENTERTAINMENT, WIFI_AND_CONNECTIVITY)   FROM base UNION ALL
  SELECT 'INFLIGHT_ENTERTAINMENT','VALUE_FOR_MONEY',         CORR(INFLIGHT_ENTERTAINMENT, VALUE_FOR_MONEY)         FROM base UNION ALL

  SELECT 'SEAT_COMFORT','WIFI_AND_CONNECTIVITY',             CORR(SEAT_COMFORT, WIFI_AND_CONNECTIVITY)             FROM base UNION ALL
  SELECT 'SEAT_COMFORT','VALUE_FOR_MONEY',                   CORR(SEAT_COMFORT, VALUE_FOR_MONEY)                   FROM base UNION ALL

  SELECT 'WIFI_AND_CONNECTIVITY','VALUE_FOR_MONEY',          CORR(WIFI_AND_CONNECTIVITY, VALUE_FOR_MONEY)          FROM base
),
corr_full AS (
  SELECT metric_x, metric_y, correlation FROM corr_upper
  UNION ALL
  -- mirror to get the lower triangle
  SELECT metric_y AS metric_x, metric_x AS metric_y, correlation
  FROM corr_upper
  WHERE metric_x <> metric_y
)
SELECT metric_x, metric_y, correlation
FROM corr_full

ORDER BY metric_x, metric_y;