SELECT
  AVG(
    CASE
      WHEN RECOMMENDED = TRUE THEN 1
      ELSE 0
    END) AS pct_recommended
FROM SKYTRAX_REVIEWS_DB.MARTS.FCT_REVIEW_ENRICHED
WHERE AIRLINE = 'United Airlines'
AND RECOMMENDED IS NOT NULL;